[package]
name = "wasm"
version = "0.1.0"
authors = ["Paul Wilson <paul.wilson@ktech.com>"]
edition = "2018"

[dependencies]

[dependencies.web-sys]
version = "0.3"
features = [
	"console"
]

[lib]
crate-type = ["cdylib"]
